In [25]:
import pandas as pd

In [26]:
# Task 1: Load Data
candidates = pd.read_csv("candidates.csv")
constituencies = pd.read_csv('constituencies.csv')
election_results = pd.read_csv('election_results.csv')

In [27]:
# Task 2: Basic Inspection
election_results.head(5)
candidates.head(5)
constituencies.head(5)

election_results.shape
candidates.shape
constituencies.shape

election_results.dtypes
candidates.dtypes
constituencies.dtypes

election_results.columns
candidates.columns
constituencies.columns

Index(['constituency_id', 'constituency_name', 'state'], dtype='str')

In [29]:
# Task 3: Null Value Handling
election_results[election_results.isna().any(axis=1)]
election_results.isna().sum() #election_results.isnull()
candidates.isnull().sum()
constituencies.isnull().sum()

election_results['votes'] = election_results['votes'].fillna(election_results['votes'].mean())
election_results = election_results.dropna()

In [34]:
# Task 4: Duplicate Handling
election_results[election_results.duplicated()]
election_results.drop_duplicates()

candidates[candidates.duplicated()]
candidates.drop_duplicates()

constituencies[constituencies.duplicated()]
constituencies.drop_duplicates()

   constituency_id    constituency_name           state
0              S01       Nagpur Central     Maharashtra
1              S02            Pune City     Maharashtra
2              S03          Indore East  Madhya Pradesh
3              S04          Delhi North           Delhi
4              S05         Jaipur South       Rajasthan
5              S06         Mumbai South     Maharashtra
6              S07         Mumbai North     Maharashtra
7              S08          Nashik West     Maharashtra
8              S09   Aurangabad Central     Maharashtra
9              S10           Thane East     Maharashtra
10             S11         Bhopal North  Madhya Pradesh
11             S12         Gwalior East  Madhya Pradesh
12             S13        Jabalpur West  Madhya Pradesh
13             S14         Ujjain South  Madhya Pradesh
14             S15           Surat East         Gujarat
15             S16       Ahmedabad West         Gujarat
16             S17       Rajkot Central         Gujarat
17             S18       Vadodara North         Gujarat
18             S19      Lucknow Central   Uttar Pradesh
19             S20         Kanpur South   Uttar Pradesh
20             S21       Varanasi North   Uttar Pradesh
21             S22            Agra West   Uttar Pradesh
22             S23           Noida City   Uttar Pradesh
23             S24        Patna Central           Bihar
24             S25           Gaya South           Bihar
25             S26          Ranchi East       Jharkhand
26             S27      Dhanbad Central       Jharkhand
27             S28    Bhubaneswar North          Odisha
28             S29        Cuttack South          Odisha
29             S30      Chennai Central      Tamil Nadu
30             S31     Coimbatore South      Tamil Nadu
31             S32         Madurai East      Tamil Nadu
32             S33      Bengaluru South       Karnataka
33             S34       Mysuru Central       Karnataka
34             S35           Hubli West       Karnataka
35             S36    Hyderabad Central       Telangana
36             S37       Warangal North       Telangana
37             S38      Vijayawada East  Andhra Pradesh
38             S39  Visakhapatnam South  Andhra Pradesh
39             S40        Kochi Central          Kerala
40             S41       Nagpur Central     Maharashtra
41             S42            Pune City     Maharashtra
42             S43          Delhi North           Delhi
43             S44         Jaipur South       Rajasthan
44             S45          Indore East  Madhya Pradesh
45             S46         Mumbai South     Maharashtra
47             S47       Vadodara North         Gujarat
48             S48        Patna Central           Bihar
49             S50          Delhi North           Delhi

In [44]:
# Task 5: Merge Data
ec = pd.merge(election_results,candidates,on='candidate_id')
ecc = pd.merge(ec,constituencies,on='constituency_id')
data = ecc[['candidate_name','party','constituency_name','state','votes']]
data = data.drop_duplicates().dropna()

In [46]:
# Task 6: Apply Function
def voting_category(vote):
    if vote > 80000:
        return 'High'
    elif vote > 70000:
        return 'Medium'
    else:
        return 'Low'
    
data['vote category'] = data['votes'].apply(voting_category)

In [ ]:
# Task 8: Aggregate Functions

data['votes'].sum()
data['votes'].mean()
data['votes'].max()
data['votes'].min()
data['candidate_name'].count()

np.int64(49)

In [75]:
# Task 9: Grouping


data.groupby('state')['votes'].sum()
data.groupby('party')['votes'].mean()
data.groupby('state')['votes'].max()
data.groupby('party')['votes'].sum()

party
AAP    5.649783e+05
BJP    1.490978e+06
INC    7.759891e+05
NCP    4.120000e+05
SHS    3.640000e+05
Name: votes, dtype: float64

In [55]:
# Task 10: Sorting

data.sort_values('votes')
data.sort_values('candidate_name')

,candidate_name,party,constituency_name,state,votes,vote category
20,Aarti Jain,BJP,Vadodara North,Gujarat,88000.000000,High
42,Abhishek Sinha,INC,Warangal North,Telangana,63000.000000,Low
36,Aditya Kulkarni,SHS,Coimbatore South,Tamil Nadu,59000.000000,Low
26,Akash Pandey,BJP,Noida City,Uttar Pradesh,79000.000000,Medium
2,Amit Verma,BJP,Indore East,Madhya Pradesh,73489.130435,Medium
53,Ananya Reddy,BJP,Vadodara North,Gujarat,75000.000000,Medium
7,Anjali Mehta,BJP,Mumbai South,Maharashtra,91000.000000,High
13,Arjun Nair,INC,Bhopal North,Madhya Pradesh,61000.000000,Low
39,Bhavna Arora,AAP,Mysuru Central,Karnataka,73489.130435,Medium
47,Chirag Modi,NCP,Pune City,Maharashtra,61000.000000,Low
19,Deepak Chauhan,SHS,Rajkot Central,Gujarat,74000.000000,Medium
32,Divya Soni,NCP,Bhubaneswar North,Odisha,73000.000000,Medium
28,Gaurav Saxena,INC,Gaya South,Bihar,70000.000000,Low
23,Harsh Vyas,BJP,Varanasi North,Uttar Pradesh,95000.000000,High
44,Isha Patel,SHS,Visakhapatnam South,Andhra Pradesh,55000.000000,Low
5,Karan Gupta,INC,Jaipur South,Rajasthan,72000.000000,Medium
16,Kavita Rao,NCP,Ujjain South,Madhya Pradesh,72000.000000,Medium
25,Komal Shah,NCP,Agra West,Uttar Pradesh,62000.000000,Low
51,Kunal Srivastava,AAP,Mumbai South,Maharashtra,82000.000000,High
21,Manish Tiwari,AAP,Lucknow Central,Uttar Pradesh,65000.000000,Low
30,Meena Iyer,BJP,Ranchi East,Jharkhand,86000.000000,High
15,Mohit Agarwal,AAP,Jabalpur West,Madhya Pradesh,73489.130435,Medium
4,Neha Singh,AAP,Delhi North,Delhi,65000.000000,Low
18,Nisha Desai,INC,Ahmedabad West,Gujarat,69500.000000,Low
33,Nishant Roy,BJP,Cuttack South,Odisha,92000.000000,High
45,Nitin Goyal,AAP,Kochi Central,Kerala,74000.000000,Medium
50,Payal Mishra,SHS,Indore East,Madhya Pradesh,66000.000000,Low
12,Pooja Yadav,SHS,Thane East,Maharashtra,56000.000000,Low
40,Prakash Jadhav,NCP,Hubli West,Karnataka,69000.000000,Low
34,Priti Bansal,INC,Chennai Central,Tamil Nadu,67000.000000,Low
1,Priya Patil,INC,Pune City,Maharashtra,78000.000000,Medium
0,Rahul Sharma,BJP,Nagpur Central,Maharashtra,85000.000000,High
43,Rakesh Yadav,BJP,Vijayawada East,Andhra Pradesh,80000.000000,Medium
54,Ravi Chandra,INC,Patna Central,Bihar,70000.000000,Low
22,Ritu Malhotra,INC,Kanpur South,Uttar Pradesh,71000.000000,Medium
8,Rohan Joshi,AAP,Mumbai North,Maharashtra,68000.000000,Low
31,Rohit Thakur,AAP,Dhanbad Central,Jharkhand,64000.000000,Low
46,Sakshi Dubey,BJP,Nagpur Central,Maharashtra,90000.000000,High
17,Sandeep Kumar,BJP,Surat East,Gujarat,81000.000000,High
55,Saurabh Shukla,BJP,Delhi North,Delhi,73489.130435,Medium
37,Shreya Kapoor,BJP,Madurai East,Tamil Nadu,76000.000000,Medium
14,Simran Kaur,BJP,Gwalior East,Madhya Pradesh,78000.000000,Medium
9,Sneha Kulkarni,NCP,Nashik West,Maharashtra,75000.000000,Medium
48,Sonal Gupta,INC,Delhi North,Delhi,73489.130435,Medium
27,Swati Choudhary,SHS,Patna Central,Bihar,54000.000000,Low
41,Tanvi Sharma,BJP,Hyderabad Central,Telangana,87000.000000,High
49,Varun Khanna,BJP,Jaipur South,Rajasthan,78000.000000,Medium
11,Vivek Mishra,BJP,Aurangabad Central,Maharashtra,83000.000000,High
38,Yash Malhotra,INC,Bengaluru South,Karnataka,81000.000000,High

In [79]:
# Task 11: Advanced Analysis

data.loc[data.groupby('state')['votes'].idxmax()]
par = data.groupby('party',as_index=False)['votes'].sum()
winner = par.sort_values('votes',ascending=False).head(1)

d = data.loc[data.groupby('candidate_name')['votes'].idxmax()]
d.sort_values('votes',ascending=False).head(3)
d.sort_values('votes',).head(3)

par = data.groupby('constituency_name',as_index=False)['votes'].sum()
winner = par.sort_values('votes',ascending=False).head(1)
winner

  constituency_name         votes
9       Delhi North  211978.26087

In [81]:
party_votes = data.groupby('party', as_index=False)['votes'].sum()
total_votes = party_votes['votes'].sum()
party_votes['vote_percentage'] = (party_votes['votes'] / total_votes) * 100

print(party_votes)

  party         votes  vote_percentage
0   AAP  5.649783e+05        15.659279
1   BJP  1.490978e+06        41.324854
2   INC  7.759891e+05        21.507783
3   NCP  4.120000e+05        11.419241
4   SHS  3.640000e+05        10.088844

In [82]:
party_avg = data.groupby('party', as_index=False)['votes'].mean()
party_avg.sort_values('votes', ascending=False).head(1)

  party         votes
1   BJP  82832.125604

In [83]:
winners = data.loc[data.groupby('constituency_name')['votes'].idxmax()]
winners.groupby('party', as_index=False)['constituency_name'].count().rename(columns={'constituency_name': 'constituencies_won'})

  party  constituencies_won
0   AAP                   6
1   BJP                  15
2   INC                  10
3   NCP                   5
4   SHS                   4

In [ ]:
# # Task 12: Business Questions
    
# 1] Which party received the highest total votes?
# --> INC

# 2] Which state recorded the highest votes?
# --> Andhra Pradesh

# 3] Who is the top-performing candidate?
# --> Harsh Vyas

# 4] Which constituency had the highest votes?
# --> Delhi North

# 5] What percentage of total votes did each party receive?
# --> 
#   party         votes  vote_percentage
# 0   AAP  5.649783e+05        15.659279
# 1   BJP  1.490978e+06        41.324854
# 2   INC  7.759891e+05        21.507783
# 3   NCP  4.120000e+05        11.419241
# 4   SHS  3.640000e+05        10.088844

# 6] Which party has the highest average votes per candidate?
# --> BJP

# 7] How many constituencies were won by each party?
# --> 

# party	constituencies_won
# 0	AAP	6
# 1	BJP	15
# 2	INC	10
# 3	NCP	5
# 4	SHS	4